name: CI

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup nightly Rust
      run: rustup toolchain install nightly-2024-02-06 --profile minimal --target wasm32-unknown-unknown --component rust-src
    - name: Install npm deps
      working-directory: ./test
      run: npm ci
    - name: Run tests
      working-directory: ./test
      run: npm test
